export enum RoleType {
  STUDENT = 'STUDENT',
  ADMIN = 'ADMIN',
  CONTENT_EDITOR = 'CONTENT_EDITOR',
  MODERATOR = 'MODERATOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTRIBUTOR = 'CONTRIBUTOR',
  REVIEWER = 'REVIEWER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
}

export enum AcademyTarget {
  IMA = 'IMA', // Indian Military Academy (English + GK + Maths)
  INA = 'INA', // Indian Naval Academy (English + GK + Maths)
  AFA = 'AFA', // Air Force Academy (English + GK + Maths)
  OTA = 'OTA', // Officers Training Academy (English + GK)
}

export enum DifficultyLevel {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
}

export enum QuestionType {
  MCQ_SINGLE = 'MCQ_SINGLE',
  MCQ_MULTIPLE = 'MCQ_MULTIPLE',
  NUMERICAL = 'NUMERICAL',
  COMPREHENSION = 'COMPREHENSION',
  ASSERTION_REASON = 'ASSERTION_REASON',
  STATEMENT_BASED = 'STATEMENT_BASED',
  MATCHING = 'MATCHING',
  IMAGE_BASED = 'IMAGE_BASED',
}

export enum QuestionReportReason {
  WRONG_ANSWER = 'WRONG_ANSWER',
  WRONG_EXPLANATION = 'WRONG_EXPLANATION',
  TYPOGRAPHICAL_ERROR = 'TYPOGRAPHICAL_ERROR',
  AMBIGUOUS_QUESTION = 'AMBIGUOUS_QUESTION',
  WRONG_TOPIC = 'WRONG_TOPIC',
  DUPLICATE = 'DUPLICATE',
  BROKEN_IMAGE = 'BROKEN_IMAGE',
  OTHER = 'OTHER',
}

export enum QuestionStatus {
  DRAFT = 'DRAFT',
  DRAFT_AI = 'DRAFT_AI',
  REVIEW = 'REVIEW',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum QuestionPaletteState {
  UNVISITED = 'UNVISITED',
  NOT_ANSWERED = 'NOT_ANSWERED',
  ANSWERED = 'ANSWERED',
  MARKED_FOR_REVIEW = 'MARKED_FOR_REVIEW',
  ANSWERED_AND_MARKED_FOR_REVIEW = 'ANSWERED_AND_MARKED_FOR_REVIEW',
  VISITED = 'VISITED',
}

export enum TestType {
  FULL_MOCK = 'FULL_MOCK',
  SUBJECT_TEST = 'SUBJECT_TEST',
  CHAPTER_TEST = 'CHAPTER_TEST',
  TOPIC_TEST = 'TOPIC_TEST',
  CUSTOM_TEST = 'CUSTOM_TEST',
  PYQ_TEST = 'PYQ_TEST',
}

export enum AttemptStatus {
  CREATED = 'CREATED',
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  AUTO_SUBMITTED_TIMEOUT = 'AUTO_SUBMITTED_TIMEOUT',
  ABANDONED = 'ABANDONED',
}

export enum IntegrityEventType {
  TAB_HIDDEN = 'TAB_HIDDEN',
  WINDOW_BLUR = 'WINDOW_BLUR',
  FULLSCREEN_EXIT = 'FULLSCREEN_EXIT',
  COPY_ATTEMPT = 'COPY_ATTEMPT',
  PASTE_ATTEMPT = 'PASTE_ATTEMPT',
  CONTEXT_MENU = 'CONTEXT_MENU',
  CONNECTION_LOST = 'CONNECTION_LOST',
  RECONNECTED = 'RECONNECTED',
  MULTIPLE_TAB_DETECTED = 'MULTIPLE_TAB_DETECTED',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum PlanFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
}

export enum MistakeStatus {
  ACTIVE = 'ACTIVE',
  RETRY_CORRECT = 'RETRY_CORRECT',
  MASTERED = 'MASTERED',
}

export enum PracticeMode {
  ALL_QUESTIONS = 'ALL_QUESTIONS',
  SUBJECT = 'SUBJECT',
  CHAPTER = 'CHAPTER',
  TOPIC = 'TOPIC',
  DIFFICULTY = 'DIFFICULTY',
  PYQ = 'PYQ',
  BOOKMARKS = 'BOOKMARKS',
  MISTAKES = 'MISTAKES',
  CUSTOM = 'CUSTOM',
}

export enum RecommendationType {
  WEAK_TOPIC_REVISION = 'WEAK_TOPIC_REVISION',
  UNATTEMPTED_PYQ = 'UNATTEMPTED_PYQ',
  MISTAKE_DRILL = 'MISTAKE_DRILL',
  TIMING_IMPROVEMENT = 'TIMING_IMPROVEMENT',
}

export enum SubscriptionTier {
  FREE = 'FREE',
  PRO = 'PRO',
  LIFETIME = 'LIFETIME',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  TRIAL = 'TRIAL',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}
